export { GitHubService } from './github/core/Service';
export type { ConfigInfo } from './github/core/Service';
export { CacheManager } from './github/cache/CacheManager';
export { GitHubTokenManager } from './github/TokenManager';
export { ProxyService } from './github/proxy/ProxyService';
export { RequestBatcher } from './github/RequestBatcher';
export { GitHubService as default } from './github/core/Service';
export { GitHubAuth } from './github/core/Auth';
export { GitHubSearchService } from './github/core/SearchService';
export { GitHubPrefetchService } from './github/core/PrefetchService';
export { GitHubStatsService } from './github/core/StatsService';
export * from './github/core/Config';
